# -*- coding: utf-8 -*-
"""Mlops_Lab_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4YeelYPHxug280KTnx0IRJ_PW_eE4D8
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor


data = pd.read_csv("/content/winequality-red.csv", sep=';')

num_samples = data.shape[0]
num_features = data.shape[1] - 1
target_variable = "quality"

print("Number of samples:", num_samples)
print("Number of features:", num_features)
print("Target variable:", target_variable)
print("\nMissing values:\n", data.isnull().sum())

X = data.drop("quality", axis=1)
y = data["quality"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model_exp1 = LinearRegression()
model_exp1.fit(X_train, y_train)
y_pred = model_exp1.predict(X_test)

mse_exp1 = mean_squared_error(y_test, y_pred)
r2_exp1 = r2_score(y_test, y_pred)

print("\nEXP-01 Linear Regression")
print("MSE:", mse_exp1)
print("R2:", r2_exp1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

model_exp2 = Ridge(alpha=1.0)
model_exp2.fit(X_train, y_train)
y_pred = model_exp2.predict(X_test)

mse_exp2 = mean_squared_error(y_test, y_pred)
r2_exp2 = r2_score(y_test, y_pred)

print("\nEXP-02 Ridge Regression")
print("MSE:", mse_exp2)
print("R2:", r2_exp2)


model_lasso = Lasso(alpha=0.1)
model_lasso.fit(X_scaled, y)

selected_features = X.columns[model_lasso.coef_ != 0]
X_selected = data[selected_features]

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, test_size=0.2, random_state=42
)

model_exp3 = Lasso(alpha=0.1)
model_exp3.fit(X_train, y_train)
y_pred = model_exp3.predict(X_test)

mse_exp3 = mean_squared_error(y_test, y_pred)
r2_exp3 = r2_score(y_test, y_pred)

print("\nEXP-03 Lasso Regression")
print("Selected Features:", list(selected_features))
print("MSE:", mse_exp3)
print("R2:", r2_exp3)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model_exp4 = RandomForestRegressor(
    n_estimators=100,
    max_depth=15,
    random_state=42
)

model_exp4.fit(X_train, y_train)
y_pred = model_exp4.predict(X_test)

mse_exp4 = mean_squared_error(y_test, y_pred)
r2_exp4 = r2_score(y_test, y_pred)

print("\nEXP-04 Random Forest")
print("MSE:", mse_exp4)
print("R2:", r2_exp4)

experiment_table = pd.DataFrame({
    "Experiment ID": ["EXP-01", "EXP-02", "EXP-03", "EXP-04"],
    "Model Type": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression",
        "Random Forest"
    ],
    "Hyperparameters": [
        "Default",
        "alpha=1.0",
        "alpha=0.1",
        "n_estimators=100, max_depth=15"
    ],
    "Preprocessing": [
        "None",
        "StandardScaler",
        "StandardScaler",
        "None"
    ],
    "Feature Selection": [
        "All features",
        "Correlation-based",
        "Lasso-based",
        "All features"
    ],
    "Train/Test Split": [
        "80/20",
        "80/20",
        "80/20",
        "80/20"
    ],
    "MSE": [
        mse_exp1,
        mse_exp2,
        mse_exp3,
        mse_exp4
    ],
    "R2 Score": [
        r2_exp1,
        r2_exp2,
        r2_exp3,
        r2_exp4
    ]
})

print("\n=== Manual Experiment Tracking Table ===")
print(experiment_table)

import os
import json
import joblib

# create output folder
os.makedirs("output", exist_ok=True)

# save metrics (use variables that already exist)
results = {
    "MSE": mse_exp1,
    "R2": r2_exp1
}

# save results
with open("output/results.json", "w") as f:
    json.dump(results, f, indent=4)

# save model
joblib.dump(model_exp1, "output/model.pkl")

print("results.json and model.pkl saved")

